# Generated by Django 5.0.4 on 2024-04-16 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
